vich_uploader:
    db_driver: orm
    metadata:
         type: attribute


    mappings:
        hebergement_images:
            uri_prefix: /images/hebergement
            upload_destination: '%kernel.project_dir%/public/images/hebergement_images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
