<?php

namespace ContainerExx8Os2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_B0T_OmMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.B0T.OmM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.B0T.OmM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'hebergement' => ['privates', '.errored..service_locator.B0T.OmM.App\\Entity\\Hebergement', NULL, 'Cannot autowire service ".service_locator.B0T.OmM": it references class "App\\Entity\\Hebergement" but no such service exists.'],
        ], [
            'hebergement' => 'App\\Entity\\Hebergement',
        ]);
    }
}
