<?php

namespace ContainerExx8Os2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8yM7YzzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8yM7Yzz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8yM7Yzz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'hebergement' => ['privates', '.errored..service_locator.8yM7Yzz.App\\Entity\\Hebergement', NULL, 'Cannot autowire service ".service_locator.8yM7Yzz": it references class "App\\Entity\\Hebergement" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'hebergement' => 'App\\Entity\\Hebergement',
        ]);
    }
}
