<?php

namespace ContainerExx8Os2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2LM0auTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2LM0auT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2LM0auT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'hebergementRepository' => ['privates', 'App\\Repository\\HebergementRepository', 'getHebergementRepositoryService', true],
        ], [
            'hebergementRepository' => 'App\\Repository\\HebergementRepository',
        ]);
    }
}
