<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerExx8Os2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerExx8Os2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerExx8Os2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerExx8Os2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerExx8Os2\App_KernelDevDebugContainer([
    'container.build_hash' => 'Exx8Os2',
    'container.build_id' => 'af40ee13',
    'container.build_time' => 1707693583,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerExx8Os2');
